version: "3.6"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  mt_outbox_tracing_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mt_outbox_tracing_db
    hostname: mt_outbox_tracing_db
    environment:
      - "SA_PASSWORD=Password12!"
      - "ACCEPT_EULA=y"
    ports:
      - 1433:1433